#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 执行打包
pnpm run docs:build

# 设置目录 A 和目录 B 的路径
dirA=$(pwd)
dirB="D:\随便写写\note-blog"  # 替换为目录 B 的路径

# 复制 dist 文件夹中的所有文件到目录 B
cp -r "$dirA/dist/"* "$dirB"

# 切换到目录 B
cd "$dirB"

# 获取当前日期并格式化为 "YYYY/MM/DD" 格式
commit_message="docs: $(date +'%Y/%m/%d')"

# 执行 git 操作
git add .
git commit -m "$commit_message"
git push # 假设推送到 master 分支，如果是其他分支，请替换为相应的分支名

# 切换回目录 A
cd "$dirA"

echo "推送成功!"