on: push

permissions:
  contents: write

jobs:
  build:
    name: 部署到 GitHub Pages
    runs-on: ubuntu-latest

    steps:
    - name: 制定node版本
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'

    - name: 拉取仓库代码
      uses: actions/checkout@v4

    - name: 安装依赖
      run: npm install

    - name: 打包项目文件
      run: npm run docs:build

    - name: 部署到 GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: gh-pages # 对应需要部署的分支。这里会把前一步打包的目录文件提交到 gh-pages 分支，最终部署这个分支的文件（打包文件）到 GitHub Pages
        FOLDER: dist # 项目打包后的目录